### ISSUE TITLE
Problems with multiple vpn profiles

### ISSUE THREAD

**Issue by lpandolfini** [jochenwierum/openvpn-manager#28] opened 2014-11-10 11:03 UTC
I'm using OpenVpnManager version 0.0.3.8 (but with version 0.0.3.6 it was the same) with Windows 7 x64, I have more than one config file in the config directory, together with the .p12 and .key files linked in the configuration.
If I start the service and the application with these files in place, I'm able to see in the tray menu all the profiles, but if start the connection to one of them the connection fails because the software is using the wrong .p12 file. If I move out of the config folder all the files, and I copy manually only the ovpn, p12 and key files of one profile, then the connection works flawlessly.

Example

config folder content:
profileA.ovpn, profileA.p12, profileA.key
profileB.ovpn, profileB.p12, profileB.key
profileC.ovpn, profileC.p12, profileC.key

Starting the connection with profileA, the log says that the software is using profileB.p12, and starting profileB the software uses profileC.p12, and so on
Sometimes stopping and restarting the service will change the p12 files picked up by the software, so sometimes after a restart of the service the software tries to use profileC.p12 for the connection to profileA.

If I have only the files of one profile in the folder then everything works.

Thanks
Luca

**Comment by hapm** [comment] 2016-04-20 11:44
Be sure to use different management ports for each connection, as you can not start two openvpn instances with the same management port. OpenVPN Manager disitinguishes the instances only by the management port when running in service mode, and if there are mutlble instances fighting for the same port, it is quite random what profile wins the fight.

**Comment by hapm** [comment] 2016-04-20 11:46
We should add a check for multible profiles sharing the same management port, so OpenVPN-Manager can warn the user, when there are conflicting profiles.

**Comment by hapm** [comment] 2016-04-20 11:53
this is a duplicate of #17

**Closed** 2016-08-23 08:07 UTC
