### ISSUE TITLE
Second config is clicked but connects to first config

### ISSUE THREAD

**Issue by phil-davis** [jochenwierum/openvpn-manager#17] opened 2013-06-27 17:54 UTC
When I select to connect to the 2nd config, the window shows the correct selected config, but the first config is actually connected to.
Running Windows7, OpenVPN Manager 0.0.3.8
Anyone else experiencing this?
![openvpn-manager-problem](https://f.cloud.github.com/assets/1535615/717719/67388682-df52-11e2-8a40-fecd60690b75.png)

**Comment by hapm** [comment] 2016-08-23 08:21
This is caused by missconfiguration, the best we can do is warn the user if this happens, so it can be fixed in the openvpn config file as suggested in #36 .

**Closed by hapm** 2016-08-23 08:21 UTC
Labels: invalid
